blank_issues_enabled: true
contact_links:
  - name: I'm unsure where to go
    url: https://www.pybamm.org/contact
    about: If you are unsure where to go, then joining our chat is recommended; Just ask!
