name: Check URLs

on:
  push:
  schedule:
    # Run everyday at 3 am UTC
    - cron: 0 3 * * *

jobs:
  urlchecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: URLs-checker
        uses: urlstechie/urlchecker-action@master
        with:
          # A comma-separated list of file types to cover in the URL checks
          file_types: .rst,.md,.py,.ipynb

          # Choose whether to include file with no URLs in the prints.
          print_all: false

          # Timeout in 10 seconds if url is not reached
          timeout: 10

          # How many times to retry a failed request (each is logged, defaults to 1)
          retry_count: 5

          # A comma separated patterns to exclude during URL checks
          exclude_patterns: https://www.datacamp.com/community/tutorials/fuzzy-string-python,http://127.0.0.1,https://github.com/pybamm-team/PyBaMM/tree/v,https::/doi.org,https::/www.sciencedirect.com

          # A comma separated list of file patterns (direct paths work as well) to exclude
          exclude_files: CHANGELOG.md
